version: '3.8'
services:
    backend:
        build:
            context: .
            args:
                NODE_ENV: 'development'
        ports:
            - 3001:3000
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - ./env:/app/env
            - ./uploads:/app/uploads
        restart: always
        expose:
            - 3000
        env_file:
            - .env

#    mongo:
#        image: mongo
#        command: mongod --auth
#        restart: always
#        volumes:
#            - ./data:/data/db
#        ports:
#            - "127.0.0.1:27017:27017"
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: igaming
#            MONGO_INITDB_ROOT_PASSWORD: Pa55word-123
#            MONGO_INITDB_DATABASE: iGaming
#        healthcheck:
#            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
#            interval: 10s
#            timeout: 5s
#            retries: 5

    redis:
        image: redis:latest
        command: [ "redis-server", "--requirepass", "PaSSwoRd!123" ]
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis-data:/data
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "-a", "PaSSwoRd!123", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    redis-data:
#    es-data:

        
