services:
    redis:
        image: redis:latest
        command: [ "redis-server", "--requirepass", "PaSSwoRd!123" ]
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis-data:/data
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "-a", "PaSSwoRd!123", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    redis-data: